wandb_version: 1

seed:
  desc: null
  value: 0
fully_reproducible:
  desc: null
  value: false
num_tasks:
  desc: null
  value: 40
num_val_tasks:
  desc: null
  value: 3
dataset_typ:
  desc: null
  value: unifA
C_dist:
  desc: null
  value: _unif_C
nx:
  desc: null
  value: 10
ny:
  desc: null
  value: 5
n_noise:
  desc: null
  value: 1
num_traces:
  desc: null
  value:
    train: 1
    val: 2000
train_steps:
  desc: null
  value: 7
batch_size:
  desc: null
  value: 28
train_data_workers:
  desc: null
  value: 1
test_batch_size:
  desc: null
  value: 2
test_data_workers:
  desc: null
  value: 1
num_epochs:
  desc: null
  value: 1
n_positions:
  desc: null
  value: 250
n_embd:
  desc: null
  value: 128
n_layer:
  desc: null
  value: 12
n_head:
  desc: null
  value: 8
n_dims_in:
  desc: null
  value: 5
n_dims_out:
  desc: null
  value: 5
changing:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.0003
weight_decay:
  desc: null
  value: 0.01
gradient_clip_algorithm:
  desc: null
  value: norm
gradient_clip_val:
  desc: null
  value: 1.0
ckpt_path:
  desc: null
  value: ../outputs/GPT2/240620_185917.1e49ad_upperTriA_gauss_C/checkpoints/step=40000.ckpt
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.2
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718910213
    t:
      1:
      - 1
      - 9
      - 11
      - 49
      - 55
      - 103
      3:
      - 16
      - 23
      4: 3.12.4
      5: 0.17.2
      6: 4.41.2
      8:
      - 5
      13: linux-x86_64
