wandb_version: 1

ckpt_path:
  desc: null
  value: ../outputs/GPT2/240607_164624.3b8b85_unifA_unif_C/checkpoints/step=7.ckpt
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717803990
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 103
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 103
      3:
      - 16
      - 23
      4: 3.12.2
      5: 0.17.0
      6: 4.38.2
      8:
      - 5
      13: darwin-arm64
